/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'weekly-schedules': WeeklySchedule;
    events: Event;
    news: News;
    'friday-prayer': FridayPrayer;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'weekly-schedules': WeeklySchedulesSelect<false> | WeeklySchedulesSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    news: NewsSelect<false> | NewsSelect<true>;
    'friday-prayer': FridayPrayerSelect<false> | FridayPrayerSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'dev' | 'super-admin' | 'admin';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "weekly-schedules".
 */
export interface WeeklySchedule {
  id: number;
  title?: string | null;
  startDate: string;
  monday?: {
    fajr?: {
      imam?: string | null;
      bilal?: string | null;
    };
    dhuhr?: {
      imam?: string | null;
      bilal?: string | null;
    };
    asr?: {
      imam?: string | null;
      bilal?: string | null;
    };
    maghrib?: {
      imam?: string | null;
      bilal?: string | null;
    };
    isha?: {
      imam?: string | null;
      bilal?: string | null;
    };
  };
  tuesday?: {
    fajr?: {
      imam?: string | null;
      bilal?: string | null;
    };
    dhuhr?: {
      imam?: string | null;
      bilal?: string | null;
    };
    asr?: {
      imam?: string | null;
      bilal?: string | null;
    };
    maghrib?: {
      imam?: string | null;
      bilal?: string | null;
    };
    isha?: {
      imam?: string | null;
      bilal?: string | null;
    };
  };
  wednesday?: {
    fajr?: {
      imam?: string | null;
      bilal?: string | null;
    };
    dhuhr?: {
      imam?: string | null;
      bilal?: string | null;
    };
    asr?: {
      imam?: string | null;
      bilal?: string | null;
    };
    maghrib?: {
      imam?: string | null;
      bilal?: string | null;
    };
    isha?: {
      imam?: string | null;
      bilal?: string | null;
    };
  };
  thursday?: {
    fajr?: {
      imam?: string | null;
      bilal?: string | null;
    };
    dhuhr?: {
      imam?: string | null;
      bilal?: string | null;
    };
    asr?: {
      imam?: string | null;
      bilal?: string | null;
    };
    maghrib?: {
      imam?: string | null;
      bilal?: string | null;
    };
    isha?: {
      imam?: string | null;
      bilal?: string | null;
    };
  };
  friday?: {
    fajr?: {
      imam?: string | null;
      bilal?: string | null;
    };
    dhuhr?: {
      imam?: string | null;
      bilal?: string | null;
    };
    asr?: {
      imam?: string | null;
      bilal?: string | null;
    };
    maghrib?: {
      imam?: string | null;
      bilal?: string | null;
    };
    isha?: {
      imam?: string | null;
      bilal?: string | null;
    };
  };
  saturday?: {
    fajr?: {
      imam?: string | null;
      bilal?: string | null;
    };
    dhuhr?: {
      imam?: string | null;
      bilal?: string | null;
    };
    asr?: {
      imam?: string | null;
      bilal?: string | null;
    };
    maghrib?: {
      imam?: string | null;
      bilal?: string | null;
    };
    isha?: {
      imam?: string | null;
      bilal?: string | null;
    };
  };
  sunday?: {
    fajr?: {
      imam?: string | null;
      bilal?: string | null;
    };
    dhuhr?: {
      imam?: string | null;
      bilal?: string | null;
    };
    asr?: {
      imam?: string | null;
      bilal?: string | null;
    };
    maghrib?: {
      imam?: string | null;
      bilal?: string | null;
    };
    isha?: {
      imam?: string | null;
      bilal?: string | null;
    };
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  category?: ('Community' | 'Education' | 'Competition' | 'Workshop') | null;
  date: string;
  eventTime: string;
  location?: string | null;
  attendees?: number | null;
  description?: string | null;
  image?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: number;
  title: string;
  slug?: string | null;
  category?: ('Announcement' | 'Education' | 'Community' | 'Development') | null;
  author?: string | null;
  publishedAt?: string | null;
  excerpt?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  image?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "friday-prayer".
 */
export interface FridayPrayer {
  id: number;
  title: string;
  publishedAt: string;
  summary?: string | null;
  topics?:
    | {
        topic?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'weekly-schedules';
        value: number | WeeklySchedule;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'news';
        value: number | News;
      } | null)
    | ({
        relationTo: 'friday-prayer';
        value: number | FridayPrayer;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "weekly-schedules_select".
 */
export interface WeeklySchedulesSelect<T extends boolean = true> {
  title?: T;
  startDate?: T;
  monday?:
    | T
    | {
        fajr?:
          | T
          | {
              imam?: T;
              bilal?: T;
            };
        dhuhr?:
          | T
          | {
              imam?: T;
              bilal?: T;
            };
        asr?:
          | T
          | {
              imam?: T;
              bilal?: T;
            };
        maghrib?:
          | T
          | {
              imam?: T;
              bilal?: T;
            };
        isha?:
          | T
          | {
              imam?: T;
              bilal?: T;
            };
      };
  tuesday?:
    | T
    | {
        fajr?:
          | T
          | {
              imam?: T;
              bilal?: T;
            };
        dhuhr?:
          | T
          | {
              imam?: T;
              bilal?: T;
            };
        asr?:
          | T
          | {
              imam?: T;
              bilal?: T;
            };
        maghrib?:
          | T
          | {
              imam?: T;
              bilal?: T;
            };
        isha?:
          | T
          | {
              imam?: T;
              bilal?: T;
            };
      };
  wednesday?:
    | T
    | {
        fajr?:
          | T
          | {
              imam?: T;
              bilal?: T;
            };
        dhuhr?:
          | T
          | {
              imam?: T;
              bilal?: T;
            };
        asr?:
          | T
          | {
              imam?: T;
              bilal?: T;
            };
        maghrib?:
          | T
          | {
              imam?: T;
              bilal?: T;
            };
        isha?:
          | T
          | {
              imam?: T;
              bilal?: T;
            };
      };
  thursday?:
    | T
    | {
        fajr?:
          | T
          | {
              imam?: T;
              bilal?: T;
            };
        dhuhr?:
          | T
          | {
              imam?: T;
              bilal?: T;
            };
        asr?:
          | T
          | {
              imam?: T;
              bilal?: T;
            };
        maghrib?:
          | T
          | {
              imam?: T;
              bilal?: T;
            };
        isha?:
          | T
          | {
              imam?: T;
              bilal?: T;
            };
      };
  friday?:
    | T
    | {
        fajr?:
          | T
          | {
              imam?: T;
              bilal?: T;
            };
        dhuhr?:
          | T
          | {
              imam?: T;
              bilal?: T;
            };
        asr?:
          | T
          | {
              imam?: T;
              bilal?: T;
            };
        maghrib?:
          | T
          | {
              imam?: T;
              bilal?: T;
            };
        isha?:
          | T
          | {
              imam?: T;
              bilal?: T;
            };
      };
  saturday?:
    | T
    | {
        fajr?:
          | T
          | {
              imam?: T;
              bilal?: T;
            };
        dhuhr?:
          | T
          | {
              imam?: T;
              bilal?: T;
            };
        asr?:
          | T
          | {
              imam?: T;
              bilal?: T;
            };
        maghrib?:
          | T
          | {
              imam?: T;
              bilal?: T;
            };
        isha?:
          | T
          | {
              imam?: T;
              bilal?: T;
            };
      };
  sunday?:
    | T
    | {
        fajr?:
          | T
          | {
              imam?: T;
              bilal?: T;
            };
        dhuhr?:
          | T
          | {
              imam?: T;
              bilal?: T;
            };
        asr?:
          | T
          | {
              imam?: T;
              bilal?: T;
            };
        maghrib?:
          | T
          | {
              imam?: T;
              bilal?: T;
            };
        isha?:
          | T
          | {
              imam?: T;
              bilal?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  category?: T;
  date?: T;
  eventTime?: T;
  location?: T;
  attendees?: T;
  description?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  author?: T;
  publishedAt?: T;
  excerpt?: T;
  content?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "friday-prayer_select".
 */
export interface FridayPrayerSelect<T extends boolean = true> {
  title?: T;
  publishedAt?: T;
  summary?: T;
  topics?:
    | T
    | {
        topic?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}