/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'prayer-times': PrayerTime;
    events: Event;
    announcements: Announcement;
    gallery: Gallery;
    staff: Staff;
    'khutbah-schedule': KhutbahSchedule;
    'prayer-roster': PrayerRoster;
    donations: Donation;
    pledges: Pledge;
    'contact-messages': ContactMessage;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'prayer-times': PrayerTimesSelect<false> | PrayerTimesSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    announcements: AnnouncementsSelect<false> | AnnouncementsSelect<true>;
    gallery: GallerySelect<false> | GallerySelect<true>;
    staff: StaffSelect<false> | StaffSelect<true>;
    'khutbah-schedule': KhutbahScheduleSelect<false> | KhutbahScheduleSelect<true>;
    'prayer-roster': PrayerRosterSelect<false> | PrayerRosterSelect<true>;
    donations: DonationsSelect<false> | DonationsSelect<true>;
    pledges: PledgesSelect<false> | PledgesSelect<true>;
    'contact-messages': ContactMessagesSelect<false> | ContactMessagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'mosque-settings': MosqueSetting;
  };
  globalsSelect: {
    'mosque-settings': MosqueSettingsSelect<false> | MosqueSettingsSelect<true>;
  };
  locale: null;
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  /**
   * Categorize this image for better organization
   */
  purpose?: ('logo' | 'gallery' | 'event' | 'staff' | 'other') | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "prayer-times".
 */
export interface PrayerTime {
  id: number;
  date: string;
  fajr: string;
  dhuhr: string;
  asr: string;
  maghrib: string;
  isha: string;
  jumuah?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  date: string;
  endDate?: string | null;
  location?: string | null;
  image?: (number | null) | Media;
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcements".
 */
export interface Announcement {
  id: number;
  title: string;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  date: string;
  priority?: ('low' | 'normal' | 'high' | 'urgent') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery".
 */
export interface Gallery {
  id: number;
  image: number | Media;
  caption?: string | null;
  category?: ('general' | 'events' | 'ramadan' | 'eid' | 'community' | 'mosque') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "staff".
 */
export interface Staff {
  id: number;
  name: string;
  role: 'imam' | 'ustaz' | 'committee' | 'staff' | 'volunteer';
  bio?: string | null;
  photo?: (number | null) | Media;
  /**
   * Display order (lower numbers first)
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "khutbah-schedule".
 */
export interface KhutbahSchedule {
  id: number;
  date: string;
  topic: string;
  speaker: string;
  notes?: string | null;
  /**
   * URL to the sermon PDF (e.g. from e-Khutbah JAIS)
   */
  sermonPdfUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "prayer-roster".
 */
export interface PrayerRoster {
  id: number;
  date: string;
  fajr?: {
    imam?: string | null;
    bilal?: string | null;
  };
  dhuhr?: {
    imam?: string | null;
    bilal?: string | null;
  };
  asr?: {
    imam?: string | null;
    bilal?: string | null;
  };
  maghrib?: {
    imam?: string | null;
    bilal?: string | null;
  };
  isha?: {
    imam?: string | null;
    bilal?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "donations".
 */
export interface Donation {
  id: number;
  name: string;
  email: string;
  phone: string;
  /**
   * Amount in RM
   */
  amount: number;
  /**
   * TayyibPay bill code
   */
  billCode?: string | null;
  status?: ('pending' | 'paid' | 'failed') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pledges".
 */
export interface Pledge {
  id: number;
  name: string;
  email: string;
  phone: string;
  /**
   * Monthly pledge amount in RM
   */
  monthlyAmount: number;
  status?: ('active' | 'paused' | 'cancelled') | null;
  /**
   * Date when the next monthly bill should be created
   */
  nextBillDate?: string | null;
  /**
   * TayyibPay bill code from the most recent bill
   */
  lastBillCode?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-messages".
 */
export interface ContactMessage {
  id: number;
  type: 'feedback' | 'inquiry';
  name: string;
  email?: string | null;
  subject?: string | null;
  message: string;
  /**
   * Star rating 1–5 (feedback only)
   */
  rating?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'prayer-times';
        value: number | PrayerTime;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'announcements';
        value: number | Announcement;
      } | null)
    | ({
        relationTo: 'gallery';
        value: number | Gallery;
      } | null)
    | ({
        relationTo: 'staff';
        value: number | Staff;
      } | null)
    | ({
        relationTo: 'khutbah-schedule';
        value: number | KhutbahSchedule;
      } | null)
    | ({
        relationTo: 'prayer-roster';
        value: number | PrayerRoster;
      } | null)
    | ({
        relationTo: 'donations';
        value: number | Donation;
      } | null)
    | ({
        relationTo: 'pledges';
        value: number | Pledge;
      } | null)
    | ({
        relationTo: 'contact-messages';
        value: number | ContactMessage;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  purpose?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "prayer-times_select".
 */
export interface PrayerTimesSelect<T extends boolean = true> {
  date?: T;
  fajr?: T;
  dhuhr?: T;
  asr?: T;
  maghrib?: T;
  isha?: T;
  jumuah?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  date?: T;
  endDate?: T;
  location?: T;
  image?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcements_select".
 */
export interface AnnouncementsSelect<T extends boolean = true> {
  title?: T;
  body?: T;
  date?: T;
  priority?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery_select".
 */
export interface GallerySelect<T extends boolean = true> {
  image?: T;
  caption?: T;
  category?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "staff_select".
 */
export interface StaffSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  bio?: T;
  photo?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "khutbah-schedule_select".
 */
export interface KhutbahScheduleSelect<T extends boolean = true> {
  date?: T;
  topic?: T;
  speaker?: T;
  notes?: T;
  sermonPdfUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "prayer-roster_select".
 */
export interface PrayerRosterSelect<T extends boolean = true> {
  date?: T;
  fajr?:
    | T
    | {
        imam?: T;
        bilal?: T;
      };
  dhuhr?:
    | T
    | {
        imam?: T;
        bilal?: T;
      };
  asr?:
    | T
    | {
        imam?: T;
        bilal?: T;
      };
  maghrib?:
    | T
    | {
        imam?: T;
        bilal?: T;
      };
  isha?:
    | T
    | {
        imam?: T;
        bilal?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "donations_select".
 */
export interface DonationsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  amount?: T;
  billCode?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pledges_select".
 */
export interface PledgesSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  monthlyAmount?: T;
  status?: T;
  nextBillDate?: T;
  lastBillCode?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-messages_select".
 */
export interface ContactMessagesSelect<T extends boolean = true> {
  type?: T;
  name?: T;
  email?: T;
  subject?: T;
  message?: T;
  rating?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mosque-settings".
 */
export interface MosqueSetting {
  id: number;
  /**
   * WhatsApp group invite link (e.g. https://chat.whatsapp.com/...)
   */
  whatsappGroupUrl?: string | null;
  name: string;
  tagline?: string | null;
  /**
   * Upload a square image (recommended: 200x200px or larger). PNG or SVG format recommended for best quality. Maximum file size: 500KB.
   */
  logo?: (number | null) | Media;
  /**
   * Choose how the logo should be displayed in the navigation bar
   */
  logoShape?: ('square' | 'circle') | null;
  address?: string | null;
  phone?: string | null;
  email?: string | null;
  mapCoordinates?: {
    lat?: number | null;
    lng?: number | null;
  };
  socialLinks?: {
    facebook?: string | null;
    instagram?: string | null;
    youtube?: string | null;
    twitter?: string | null;
  };
  about?: {
    history?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    mission?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  donation?: {
    bankName?: string | null;
    accountName?: string | null;
    accountNumber?: string | null;
    description?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    paymentLink?: string | null;
    /**
     * DuitNow / bank QR code image for scan-to-pay
     */
    qrImage?: (number | null) | Media;
  };
  jumuah?: {
    time?: string | null;
    guidelines?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  sermonPortal?: {
    /**
     * Name of the sermon portal (e.g. e-Khutbah JAIS)
     */
    name?: string | null;
    /**
     * URL to the sermon portal
     */
    url?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mosque-settings_select".
 */
export interface MosqueSettingsSelect<T extends boolean = true> {
  whatsappGroupUrl?: T;
  name?: T;
  tagline?: T;
  logo?: T;
  logoShape?: T;
  address?: T;
  phone?: T;
  email?: T;
  mapCoordinates?:
    | T
    | {
        lat?: T;
        lng?: T;
      };
  socialLinks?:
    | T
    | {
        facebook?: T;
        instagram?: T;
        youtube?: T;
        twitter?: T;
      };
  about?:
    | T
    | {
        history?: T;
        mission?: T;
      };
  donation?:
    | T
    | {
        bankName?: T;
        accountName?: T;
        accountNumber?: T;
        description?: T;
        paymentLink?: T;
        qrImage?: T;
      };
  jumuah?:
    | T
    | {
        time?: T;
        guidelines?: T;
      };
  sermonPortal?:
    | T
    | {
        name?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}